Modify the .toml files to add new versions and groups
os-autoinst/openqa-mon pull request #100
Opened 2023-03-28 11:13 UTC by pablo-herranz

2023-03-28 11:21 UTC, m-dati commented on _review/qec-sle-wsl.toml
> +HideStatus = [ "scheduled", "passed", "softfailed", "running", "reviewed" ] # Hide scheduled and passed jobs
If you have time, not mandatory, update the comment too, i.e.: `Hide jobs in a specific status`

2023-03-28 11:25 UTC, pablo-herranz commented on _review/qec-sle-wsl.toml
> +HideStatus = [ "scheduled", "passed", "softfailed", "running", "reviewed" ] # Hide scheduled and passed jobs
Changed :)

2023-03-28 12:33 UTC, pdostal commented
Please provide less generic commit message and pull request title (e.g. specify which files you changing and how).

This pull request continues from #99.

2023-03-28 13:20 UTC, pdostal approved these changes
🚀

2023-03-29 06:58 UTC, grisu48 commented
![image](https://user-images.githubusercontent.com/1527829/228451377-5a75dd82-352c-4143-85d2-a3208e4acd2b.png)

Can you please sign the commit? You can do this by add the `signingKey` to your `~/.gitconfig` and amend the commit, e.g.

```
[user]
    name = ...
    email = ...
    signingKey = ...
```

2023-03-29 07:02 UTC, grisu48 requested changes
Thanks Pablo, this looks already great! Some minor changes are required but then let's go! :rock:

2023-03-29 07:02 UTC, grisu48 commented on _review/qec-containers.toml
> +MaxLifetime = 86400
Not needed with this `build` variable.

2023-03-29 07:02 UTC, grisu48 commented on _review/qec-jeos.toml
> +MaxLifetime = 86400
Not needed with this `build` variable

2023-03-29 07:02 UTC, grisu48 commented on _review/qec-sle-micro.toml
> +Name = "SLEM 5.1 on Public Cloud"
I know that I did it wrong in the beginning but still .... Mind reversing the order to ascending? (First 5.4, then 5.3, 5.2, ...) It looks a bit weird to have first 5.4 then 5.1 then 5.2 ....

2023-03-29 07:02 UTC, grisu48 commented on _review/qec-sle-micro.toml
> +MaxLifetime = 86400
Not needed with this `build` variable

2023-03-29 07:02 UTC, grisu48 commented on _review/qec-sle-wsl.toml
> +MaxLifetime = 86400
Please add a newline at the end.

2023-03-29 07:09 UTC, pablo-herranz commented on _review/qec-containers.toml
> +MaxLifetime = 86400
Not needed in any of the versions or just 15-SP4?

2023-03-29 07:11 UTC, pablo-herranz commented on _review/qec-sle-micro.toml
> +Name = "SLEM 5.1 on Public Cloud"
Yes, it is weird to me too, but it's how it shows up in OSD menu, that's why I choose it this way. Want me to reverse it anyway?

![image](https://user-images.githubusercontent.com/97286347/228454389-31fe2d68-12b2-468c-86f6-b0462ae71682.png)

2023-03-29 08:29 UTC, grisu48 commented on _review/qec-sle-micro.toml
> +Name = "SLEM 5.1 on Public Cloud"
Yes please, it looks weird.

2023-04-27 10:39 UTC, grisu48 commented
Is this PR still active?

2023-04-27 10:43 UTC, pablo-herranz commented
Yup, nobody merged it :(

2023-04-27 13:26 UTC, grisu48 commented
> Yup, nobody merged it :(

Oh sorry, I only saw the unresolved discussions and assumed this is till work in progress.

If you rebase it and poke me, I can merge it.

2023-04-28 10:38 UTC, grisu48 approved these changes
LGTM!

2023-04-28 10:38 UTC, merged