Cleanup container definitions
os-autoinst/openqa-mon pull request #52
Opened 2021-08-13 09:46 UTC by grisu48

Split the SLE-Base images into separate file and remove the latest job
group, because it's not needed for the daily review.

2021-08-13 09:46 UTC, grisu48 commented
Asking @b10n1k for Feedback as he contributed to those files in the past :slightly_smiling_face:

2021-08-24 10:54 UTC, cfconrad commented
I'm against splitting it. I would like to have less then needed *toml files :)

2021-08-26 09:46 UTC, d3flex commented
> Asking @b10n1k for Feedback as he contributed to those files in the past

i would have agreed with @cfconrad in general.
However the those jobs starting getting bigger and bigger and it might be easier to review in smaller reasonable chunks. 
In additional the `Containers Updates` and the `Containers SLE Base Image Updates` have different scheduling. one when new build syncs with openqa and the other when a new container image is built. they can have different frequency, so i am not sure that one file will be meaningful.

2021-08-26 09:50 UTC, d3flex commented on _review/sle-base-images.toml
> +
Can you add 

```
[[Groups]]
Name = "Containers SLE Base Image Updates 15-SP4"
Params = { groupid = "395" }
```

this is a new job group for sle15sp4.

2021-08-26 09:51 UTC, d3flex requested changes
i have a suggestion but you can ignore it and added later

2021-09-01 14:45 UTC, grisu48 commented on _review/sle-base-images.toml
> +
I will add them when SLE 15-SP4 is released. Since this is currently the "Latest" image repo I find it not matching in the updates toml file.

2021-09-01 14:45 UTC, grisu48 commented
> i have a suggestion but you can ignore it and added later

Yes, 15-SP4 will be added when it's released and the first updates are coming up.

2021-09-01 14:48 UTC, grisu48 commented
> I'm against splitting it. I would like to have less then needed *toml files :)

All of the provided `toml` files are configuration EXAMPLES. Feel free to take them and modify to your own needs.
The separation is done because I consider the container and SLE Base Image tests two logically different scenarios.

Think of the provided examples are Lego blocks to build up your own toml file. I believe it makes more sense to provide a set of small blocks that can be used to build a bigger file. In contrast to the previous state, where you had one big file, and you needed to extract the necessary building blocks.

2021-09-01 14:49 UTC, merged